config/routes.rb
Rails.application.routes.draw do

	get 'sessions/new'

	root 'static_pages#home'
	
	get '/help', to: 'static_pages#help'
	get '/about', to: 'static_pages#about'
	get '/contact', to: 'static_pages#contact'

	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'

	get '/register', to: 'users#new'
	post '/register',  to: 'users#create'
	resources :users

	resources :microposts, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
	belongs_to :user
	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord

	has_many :microposts, dependent: :destroy

	attr_accessor :remember_token

	before_save { self.email = email.downcase }

	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end
	
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def feed
		Micropost.where("user_id = ?", id)
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	
	include SessionsHelper

	def hello
		render html: "hello, world!"
	end
	
	private

	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger] = "Please log in."
			redirect_to login_url
		end
	end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

	before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user,   only: :destroy

	def create
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			flash[:success] = "Micropost created!"
			redirect_to root_url
		else
			@feed_items = []
			render 'static_pages/home'
		end
	end

	def destroy
		@micropost.destroy
		flash[:success] = "Micropost deleted"
		redirect_to request.referrer || root_url
	end

	private

	def micropost_params
		params.require(:micropost).permit(:content)
	end

	def correct_user
		@micropost = current_user.microposts.find_by(id: params[:id])
		redirect_to root_url if @micropost.nil?
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in user
			params[:session][:remember_me] == '1' ? remember(user) : forget(user)
			redirect_back_or user
		else
			flash.now[:danger] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		log_out if logged_in?
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
	def help
	end

	def about
	end

	def contact
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
	before_action :correct_user,   only: [:edit, :update]
	before_action :admin_user,     only: :destroy

	def index
		@users = User.paginate(page: params[:page])
	end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Welcome to Social App! You have successfully logged in!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User successfully deleted!"
		redirect_to users_url
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password,
			:password_confirmation)
	end

	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger] = "You need to be logged in to view this page."
			redirect_to login_url
		end
	end

	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_url) unless current_user?(@user)
	end

	def admin_user
		redirect_to(root_url) unless current_user.admin?
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "Social App"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user?(user)
		user == current_user
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def destroy
		log_out if logged_in?
		redirect_to root_url
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

    def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <p class="text-center">&copy; 2019 Social App</p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="<%= root_url %>">Social App</a>
		</div>
		<ul class="nav navbar-nav">
			<li class="active"><a href="<%= root_url %>">Home</a></li>
			<li><a href="<%= help_url %>">Help</a></li>
			<li><a href="<%= about_url %>">About</a></li>
			<li><a href="<%= contact_url %>">Contact Us</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<% if logged_in? %>
			<li><%= link_to "Users", users_path %></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Account <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Profile", current_user %></li>
					<li><%= link_to "Settings", edit_user_path(current_user) %></li>
					<li class="divider"></li>
					<li>
						<%= link_to "Log out", logout_path, method: :delete %>
					</li>
				</ul>
			</li>
			<% else %>
			<li><a href="<%= register_url %>"><span class="fa fa-user"></span> Sign Up</a></li>
			<li><a href="<%= login_url %>"><span class="fa fa-key"></span> Login</a></li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

	<%= render 'layouts/header' %>

	<div class="container">

		<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>

		<%= yield %>

	</div>

</body>
</html>

app/views/microposts/_micropost.html.erb
<div class="panel panel-default" id="micropost-<%= micropost.id %>">
	<div class="panel-body">
		<span class="user"><%= link_to micropost.user.name, micropost.user %></span>
		<br>
		<p>
			<span class="content"><%= micropost.content %></span>
		</p>
	</div>
	<div class="panel-footer">
		<p>
			<span class="timestamp">
				Posted <%= time_ago_in_words(micropost.created_at) %> ago.
				<% if current_user?(micropost.user) %>
				<%= link_to "delete", micropost, method: :delete,
				data: { confirm: "Are you sure?" } %>
				<% end %>
			</span>
		</p>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<h4><%= current_user.name %></h4>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="panel panel-default">
	<div class="panel-heading">
		<h4>About</h4>
	</div>
	<div class="panel-body">
		<p>
			This is a customized social app for AID B (Part C - Requirement 3). It includes:
			<ul>
				<li>Data Validation</li>
				<li>Styles/Layout</li>
				<li>Authentication</li>
				<li>Internationalization</li>
				<li>Agile Test Driven Design (TDD) with either Unit Tests or RSpec</li>
			</ul>
		</p>
		<hr>
		<p><i class="fa fa-bitbucket"></i> BitBucket Link: <a target="_blank" href="https://bitbucket.org/izakibikas/social_app/src">Social App</a></p>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact Us") %>

<h1>Contact Us</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<%= render 'shared/user_info' %>
		</section>
		<section class="micropost_form">
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>
	<div class="col-md-8">
		<h3>Micropost Feed</h3>
		<%= render 'shared/feed' %>
	</div>
</div>
<% else %>
<div class="jumbotron">
	<h1>Social App</h1>
	<p>Welcome to Social App! To get started, login or sign up if you are a new user!</p>
	<hr>
	<a href="<%= login_url %>" class="btn btn-success">Login</a> 	<a href="<%= register_url %>" class="btn btn-success">Sign up</a>
</div>
<% end %>

app/views/static_pages/register.html.erb
<% provide(:title, "Register") %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
	| <%= link_to "delete", user, method: :delete,
	data: { confirm: "Are you sure you want to delete this user?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Update your profile</h4>

			</div>
			<div class="panel-body">
				<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>

				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>

				<%= f.label :email %>
				<%= f.email_field :email, class: 'form-control' %>

				<%= f.label :password %>
				<%= f.password_field :password, class: 'form-control' %>

				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>

				<%= f.submit "Save changes", class: "btn btn-primary" %>
				<% end %>

			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>All users</h4>
			</div>

			<div class="panel-body">

				<%= will_paginate %>

				<ul class="users">
					<%= render @users %>
				</ul>

				<%= will_paginate %>

			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>


<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Sign up</h4>
			</div>
			<div class="panel-body">

				<%= form_for(@user, url: register_path) do |f| %>

				<%= render 'shared/error_messages', object: f.object %>

				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>

				<%= f.label :email %>
				<%= f.email_field :email, class: 'form-control' %>

				<%= f.label :password %>
				<%= f.password_field :password, class: 'form-control' %>

				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>

				<br>

				<%= f.submit "Create my account", class: "btn btn-primary" %>
				<% end %>

			</div>
		</div>

	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="panel panel-default">

	<div class="panel-body">
		
		<div class="row">
			<aside class="col-md-4">
				<section class="user_info">
					<h1>
						<%= @user.name %>
					</h1>
				</section>
			</aside>
			<div class="col-md-8">
				<% if @user.microposts.any? %>
				<h3>Microposts (<%= @user.microposts.count %>)</h3>
				<ol class="microposts">
					<%= render @microposts %>
				</ol>
				<%= will_paginate @microposts %>
				<% end %>
			</div>
		</div>

	</div>

</div>